#!/usr/bin/env python3
"""Rasterise a TTF/OTF to a BDF subset, for tools/bdf2pcf.py to turn into PCF.

    python3 tools/ttf2bdf.py Literata.ttf 14 device/fonts/literata-14-r.bdf [Family] [weight]

The reader loads PCF, and PCF is built from BDF, and the only BDF in this
project came from someone else's otf2bdf run. That left the font size fixed at
whatever that run used, which is no good once the font is something the reader
lets you choose. This closes the pipeline: outline in, bitmap out, at any size.

Only the glyphs in GLYPH_SET are emitted - the same set the reader loads and
the same reason: a 1163-glyph font costs seconds of CircuitPython file I/O that
a 110-glyph one does not.

Pillow does the rasterising. Its coordinates are measured down from the top of
the line box; BDF measures up from the baseline, so the conversion is
    yoff = ascent - (offset_y + height)
which is the only fiddly part.
"""
import sys

from PIL import Image, ImageDraw, ImageFont

GLYPH_SET = "".join(chr(c) for c in range(0x20, 0x7F)) + " " + "©àèéêöûü—‘’“”…"


def render(path, px, out, family=None, wght=None):
    font = ImageFont.truetype(path, px)

    # For a variable font, pin the axes. Two effects, both wanted:
    #
    #   - it selects the weight, so `wght` can thin or thicken the face;
    #   - it makes FreeType drop the font's TrueType hinting program, because
    #     those instructions are only valid for the default instance.
    #
    # That second one is the reason this is here at all. Open Sans's hinting
    # snaps vertical stems up to a full 2px at 14px while leaving horizontals
    # at 1px, so capitals like I B E Y come out visibly bottom-heavy. Unhinted,
    # both land on 1px and the letter is balanced.
    try:
        axes = font.get_variation_axes()
    except Exception:
        axes = None
    if axes:
        values = []
        for axis in axes:
            name = axis.get("name", b"")
            if wght is not None and b"Weight" in name:
                values.append(float(wght))
            else:
                values.append(float(axis["default"]))
        font.set_variation_by_axes(values)

    ascent, descent = font.getmetrics()
    family = family or (font.getname()[0] or "Font").replace(" ", "")

    glyphs = []
    for ch in GLYPH_SET:
        try:
            # mode "1" is FreeType's monochrome rasteriser, with hinting - the
            # same path otf2bdf used for the Literata that has always looked
            # right. Greyscale-and-threshold does not substitute: a stem
            # covering ~50% of two adjacent columns passes the threshold in
            # both, so every vertical comes out 2px while horizontals round
            # down to 1px, and capitals like I B E Y look bottom-heavy.
            #
            # Hinting also needs an unhinted-friendly source: the static
            # OpenSans-Regular.ttf snaps stems up to 2px even in mono, where
            # the variable font at the same weight gives 1px.
            mask, (ox, oy) = font.getmask2(ch, mode="1")
        except Exception:
            continue
        w, h = mask.size
        adv = int(round(font.getlength(ch)))
        rows = []
        if w and h:
            data = bytes(mask)
            # Pillow keeps a mode-"1" mask as one byte per pixel (0 or 255),
            # NOT packed bits - handing it to Image.frombytes("1", ...) reads
            # it 8x wrong and silently yields striped garbage. Both layouts are
            # handled here so a future Pillow cannot reintroduce that.
            if len(data) == w * h:
                def ink(x, y):
                    return data[y * w + x] != 0
            else:
                rb = (w + 7) // 8
                def ink(x, y):
                    return (data[y * rb + (x >> 3)] >> (7 - (x & 7))) & 1
            for y in range(h):
                bits = 0
                for x in range(w):
                    if ink(x, y):
                        bits |= 1 << (w - 1 - x)
                pad = (-w) % 8
                rows.append("%0*X" % ((w + pad) // 8 * 2, bits << pad))
        else:
            w = h = 0
        glyphs.append((ord(ch), ch, adv, w, h, ox, ascent - (oy + h), rows))

    maxw = max((g[3] for g in glyphs), default=1)
    maxh = max((g[4] for g in glyphs), default=1)
    with open(out, "w", encoding="utf-8") as f:
        f.write("STARTFONT 2.1\n")
        f.write("COMMENT Generated by tools/ttf2bdf.py from %s at %dpx\n"
                % (path.rsplit("/", 1)[-1], px))
        f.write("FONT -misc-%s-Medium-R-Normal--%d-100-100-100-P-%d-ISO10646-1\n"
                % (family, px, maxw * 10))
        f.write("SIZE %d 100 100\n" % px)
        f.write("FONTBOUNDINGBOX %d %d %d %d\n" % (maxw, maxh, 0, -descent))
        f.write("STARTPROPERTIES 4\n")
        f.write("FAMILY_NAME \"%s\"\nPIXEL_SIZE %d\n" % (family, px))
        f.write("FONT_ASCENT %d\nFONT_DESCENT %d\n" % (ascent, descent))
        f.write("ENDPROPERTIES\n")
        f.write("CHARS %d\n" % len(glyphs))
        for code, ch, adv, w, h, xoff, yoff, rows in glyphs:
            f.write("STARTCHAR U+%04X\n" % code)
            f.write("ENCODING %d\n" % code)
            f.write("SWIDTH 0 0\nDWIDTH %d 0\n" % adv)
            f.write("BBX %d %d %d %d\n" % (w, h, xoff, yoff))
            f.write("BITMAP\n")
            for r in rows:
                f.write("%s\n" % r)
            f.write("ENDCHAR\n")
        f.write("ENDFONT\n")

    ink_top = min(ascent - (g[6] + g[4]) for g in glyphs if g[4])
    ink_bot = max(ascent - g[6] - 1 for g in glyphs if g[4])
    print("%s: %d glyphs, ascent %d descent %d" % (out, len(glyphs), ascent, descent))
    print("   ink spans y%+d..y%+d relative to a line top -> %d rows"
          % (ink_top, ink_bot, ink_bot - ink_top + 1))


if __name__ == "__main__":
    if len(sys.argv) not in (4, 5, 6):
        raise SystemExit(__doc__)
    render(sys.argv[1], int(sys.argv[2]), sys.argv[3],
           sys.argv[4] if len(sys.argv) > 4 else None,
           int(sys.argv[5]) if len(sys.argv) > 5 else None)
